### ISSUE TITLE
Install PipeCD other way than using Helm charts

### ISSUE THREAD

**Issue by jz543fm** [pipe-cd/pipecd#4362]
**What would you like to be added**:

I would like to request to add to installation section of PipeCD,  how to install PipeCD using other tool than Helm, for example plain  .yaml or using kustomize ( kustomize.io )

**Why is this needed**:

Because not everyone is a fan of Helm

**Comment by khanhtc1202** [comment]
Thanks for the comment. We're using Helm for now because of its ability to support multiple installation patterns (Currently, the PipeCD control plane can be configured to be used with SQL / Firestore / S3 / GCS / Minio), but I understand your point. Focus users to install Helm to get started causes PipeCD to lose some potential users. We tried Kustomize previously, but it will increase the cost of maintaining manifests (2 possible datastore x 3 possible filestore makes at least 6 combinations, and so on for other configurations), that's actually strong point for using Helm over other templating tools.

**Comment by jz543fm** [comment]
No problem. Yes, I totally understand the situation with the Helm and comparsion with the kustomize, I am just watching on the PipeCD control plane, I agree that is much harder to maintain in kustomize for more combinations, maybe in future will be helpful to have installation in kustomize..., because as you said, it's forced for users to use only Helm

Ok, I agree
