### ISSUE TITLE
Do we need `docs/content/en/docs`?

### ISSUE THREAD

**Issue by kentakozuka** [pipe-cd/pipecd#4454]
`docs/` is supposed to be the same with docs of the latest version(e.g. `docs-v0.44.x/`).

Also, When we jump "Documentation" from the [top page](https://pipecd.dev/) with a specific version being selected, we are navigated to `docs/`. This should be docs of the selected version.

**Comment by khanhtc1202** [comment]
This is a legacy problem. Previously, we only have one single docs which is `/docs/` and after that when we start versioning the docs, I thought link to `/docs/` be referred out where (on other site blog, for instead) should be keep alive. That's why we decided that we have to keep `/docs` and make it points to the latest version docs. But, I get your point on this 🤔

**Comment by kentakozuka** [comment]
I meant this;

https://github.com/pipe-cd/pipecd/assets/16733673/2eaf9fdd-f3af-4b4d-bd9c-d8e237a7b295

**Comment by kentakozuka** [comment]
How about this?
- remove `/docs/`.
- configure to redirect all `/docs/` to the latest URL (e.g. `/docs-v0.44.0x` on 2023-06-29)

because `/docs/` and the latest versioned docs contain the same content.

**Comment by khanhtc1202** [comment]
Do you mean after that (on version v0.45.x release and so on), we don't do redirection any more, any require versioning docs url from now on 👀

**Comment by kentakozuka** [comment]
I meant we would do redirect `/docs/` to the latest version.
`/docs` will be removed because all accesses to `/docs/` will be redirected to the latest docs.

**Comment by kentakozuka** [comment]
@khanhtc1202 
How about this simple way to do?
https://github.com/pipe-cd/pipecd/pull/4458

- Remove `/docs-dev`
- Treat `/docs/` as `master`(I guess we already do that in our mind)

I looked at [KubeFlow](https://v1-6-branch.kubeflow.org/) and they seem to do in this way.
<img width="211" alt="Screenshot 2023-06-30 at 08 04 35" src="https://github.com/pipe-cd/pipecd/assets/16733673/9c1b6215-5e98-4ab0-b37d-fd9eb78e0f70">

**Comment by khanhtc1202** [comment]
Sorry but I don't think that way. First, the master means to dev version of the docs. Since it is docs for the not yet released version, I prefer to use the word `dev` over `latest` or `master` to mention that it's dev (not released) directly.

And besides, I don't think treating the `/docs` as master/dev/latest is a good idea. It should be treated as stable/latest-released docs, since it clearly means it's the documentation (users may don't aware of docs has other versions so `/docs` can be used as the only one)

This is the versioning of argocd (latest: dev / stable: latest released / versioning: ...)

<img width="188" alt="Screen Shot 2023-06-30 at 10 27 47" src="https://github.com/pipe-cd/pipecd/assets/32532742/23f67861-0282-4f27-b55a-ab55f1131c1c">

**Comment by kentakozuka** [comment]
I just started to think the current directory structure and writing flow is good enough.
- We already have `make gen/stable-docs`.
- Removing `/docs/` and setting up the redirect to the latest version is not that easy.

So I'm thinking to close this issue until someone has the same thought.
@khanhtc1202 wdyt?

**Comment by khanhtc1202** [comment]
For sure, let's make a discussion for this later if we have a better idea around the docs :+1:
