### ISSUE TITLE
Make it possible to disable drift-detection feature for each kind of application from Piped configuration

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#4508]
**What would you like to be added**:

**Why is this needed**:

For example, in Terraform, that feature is still under Alpha status. It could cause numerous bugs and performance downgrades. Therefore, it should be disabled by default.

**Comment by kentakozuka** [comment]
While this feature is enabled by default now, disabling it by default affect existing users.
So how about adding an option to piped config to disable all terraform drift detections?

**Comment by kentakozuka** [comment]
@khanhtc1202 wdyt?

**Comment by khanhtc1202** [comment]
@kentakozuka Yes, it should be a configurable option for users who want to make this feature turning off. 👍 

> Which level of config is better to set?;

I think it's better to make it application config first, then add to piped configuration (if needed) since the piped is designed to control many applications at once, and disabling this feature of one piped may affect many unexpected applications due to users may forget which applications is handling by that piped. Of course, in the current usecase, we want to off that feature due to the piped usage, but the feature showing on the UI is part of the application, thus this is easier to understand if we make it on/off switch by the application configuration.

**Comment by kentakozuka** [comment]
OK. Let me add the option to piped config 👍
