### ISSUE TITLE
[ECS]When using application autoscaling, the desired count must be adjusted each time.

### ISSUE THREAD

**Issue by tom-256** [pipe-cd/pipecd#5027]
**What would you like to be added**:
When using Application AutoScaling in ECS, ignore desiredCount parameter.

**Why is this needed**:
- If the number of desredCounts is less than the running desiredCount at the time of deployment, a failure will occur because

- In general, ECS is often used in conjunction with application autoscaling, so it is expensive to compare the current value with the running value at the time of deploying.

For example, Terraform allows you to ignore settings
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/docs/README.md#service-1

**Comment by t-kikuc** [comment]
I created a draft PR https://github.com/pipe-cd/pipecd/pull/5030 to solve it. After testing, I'll make it ready for review.

That will enable you to ignore `desiredCount` on updating a service by a new config attribute `ignoreDesiredCountOnUpdate`.

Of course, `desiredCount` will be ignored while ECS's DriftDetection(In Progress feature yet).

**Another way I did not choose**

Another way is to make it possible to configure autoscaling in PipeCD. (e.g. by introducing a new definition file)

It is tougher to develop because:
- Tougher to develop
  - Requires a new definition file
  - LiveStateStore will be more complicated
- Cannot support scaling in other ways (e.g. directly calling APIs to scale-up)


If required, we can discuss how to manage autoscaling in PipeCD here: https://github.com/pipe-cd/pipecd/discussions/4709.
